name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Deploy
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/liangchunn/liangchunn.github.io.git
          yarn build
          yarn deploy -u "github-actions-bot <support+actions@github.com>"
